import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layouts/Navbar";
import Footer from "@/components/Layouts/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title:{
    default:"CareNest",
    template: "%s | CareNest",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <NextAuthProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased bg-blue-50`} suppressHydrationWarning={true}>
          <header className="sticky top-0 z-50">
            <div className="w-11/12 mx-auto">
              <Navbar></Navbar>
            </div>
          </header>
          <main className="py-2 w-11/12 mx-auto min-h-[calc(100vh-302px)]">
            {children}
          </main>

          <footer>
            <Footer></Footer>
          </footer>
        </body>
      </html>
    </NextAuthProvider>
  );
}
