import Service from "@/components/Services/Services";
import React from "react";

  export const metadata = {
  title: "All Services",
  description: "Generated by create next app",
};

const ServicePage = () => {

  return (
    <div className="min-h-screen">
      <Service />
    </div>
  );
};

export default ServicePage;
